@echo off
DEL ".\*.log"
DEL ".\*.lof"
DEL ".\*.dvi"
DEL ".\*.aux"
DEL ".\*.lot"
DEL ".\*.toc"
DEL ".\*.ps"
DEL ".\*.blg"
DEL ".\*.bbl"
DEL ".\*.out"
DEL ".\*.glg"
DEL ".\*.glo"
DEL ".\*.gls"
DEL ".\*.ist"

DEL ".\chapters\*.aux"
DEL ".\chapters\*.log"